name: "cron-cz-6"
run-name: "Cron CZ (6am)"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 6 * * *"

jobs:
  fetch:
    runs-on: ubuntu-latest

    env:
      SUPABASE_SERVICE_ROLE: ${{ secrets.SUPABASE_SERVICE_ROLE }}
      NEWSDATA_API_KEY: ${{ secrets.NEWSDATA_API_KEY }}
      SUPABASE_URL: ${{ secrets.SUPABASE_URL }}

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        id: python_setup
        with:
          python-version: '3.11.2'
          cache: 'pip'

      - name: Cache hit
        run: echo '${{ steps.python_setup.outputs.cache-hit }}'

      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - run: python ./supabase/news.py
